# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GMTools.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 484)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 51, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 10, 51, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(300, 10, 51, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(470, 10, 51, 20))
        self.label_4.setObjectName("label_4")
        self.Button_connectDB = QtWidgets.QPushButton(self.centralwidget)
        self.Button_connectDB.setGeometry(QtCore.QRect(660, 10, 75, 23))
        self.Button_connectDB.setObjectName("Button_connectDB")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 10, 61, 20))
        self.lineEdit_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 10, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(510, 10, 113, 20))
        self.lineEdit_4.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 30, 801, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Button_getPlayerList = QtWidgets.QPushButton(self.centralwidget)
        self.Button_getPlayerList.setGeometry(QtCore.QRect(20, 50, 81, 23))
        self.Button_getPlayerList.setObjectName("Button_getPlayerList")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 241, 22))
        self.comboBox.setObjectName("comboBox")
        self.Button_selectPlayer = QtWidgets.QPushButton(self.centralwidget)
        self.Button_selectPlayer.setGeometry(QtCore.QRect(390, 50, 75, 23))
        self.Button_selectPlayer.setObjectName("Button_selectPlayer")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 801, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEdit_copper = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_copper.setEnabled(True)
        self.lineEdit_copper.setGeometry(QtCore.QRect(490, 90, 141, 20))
        self.lineEdit_copper.setObjectName("lineEdit_copper")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 90, 51, 20))
        self.label_5.setObjectName("label_5")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 140, 801, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_iron = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_iron.setGeometry(QtCore.QRect(490, 120, 141, 20))
        self.lineEdit_iron.setObjectName("lineEdit_iron")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 120, 51, 20))
        self.label_6.setObjectName("label_6")
        self.lineEdit_food = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_food.setGeometry(QtCore.QRect(260, 120, 161, 20))
        self.lineEdit_food.setObjectName("lineEdit_food")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 120, 51, 20))
        self.label_7.setObjectName("label_7")
        self.lineEdit_wood = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_wood.setGeometry(QtCore.QRect(60, 120, 131, 20))
        self.lineEdit_wood.setText("")
        self.lineEdit_wood.setObjectName("lineEdit_wood")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 120, 51, 20))
        self.label_8.setObjectName("label_8")
        self.lineEdit_lv = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_lv.setEnabled(True)
        self.lineEdit_lv.setGeometry(QtCore.QRect(60, 90, 131, 20))
        self.lineEdit_lv.setText("")
        self.lineEdit_lv.setObjectName("lineEdit_lv")
        self.lineEdit_gold = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gold.setEnabled(True)
        self.lineEdit_gold.setGeometry(QtCore.QRect(260, 90, 161, 20))
        self.lineEdit_gold.setText("")
        self.lineEdit_gold.setObjectName("lineEdit_gold")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 90, 51, 20))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 51, 20))
        self.label_12.setObjectName("label_12")
        self.Button_modify_Base = QtWidgets.QPushButton(self.centralwidget)
        self.Button_modify_Base.setGeometry(QtCore.QRect(660, 100, 75, 23))
        self.Button_modify_Base.setObjectName("Button_modify_Base")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 160, 51, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 190, 51, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(20, 220, 51, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 250, 51, 20))
        self.label_16.setObjectName("label_16")
        self.lineEdit_w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w1.setGeometry(QtCore.QRect(70, 190, 51, 20))
        self.lineEdit_w1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w1.setText("")
        self.lineEdit_w1.setObjectName("lineEdit_w1")
        self.lineEdit_w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w2.setGeometry(QtCore.QRect(70, 220, 51, 20))
        self.lineEdit_w2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w2.setText("")
        self.lineEdit_w2.setObjectName("lineEdit_w2")
        self.lineEdit_w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w3.setGeometry(QtCore.QRect(70, 250, 51, 20))
        self.lineEdit_w3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w3.setText("")
        self.lineEdit_w3.setObjectName("lineEdit_w3")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(80, 160, 51, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 280, 51, 20))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(20, 340, 51, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit_w4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w4.setGeometry(QtCore.QRect(70, 280, 51, 20))
        self.lineEdit_w4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w4.setText("")
        self.lineEdit_w4.setObjectName("lineEdit_w4")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(20, 310, 51, 20))
        self.label_20.setObjectName("label_20")
        self.lineEdit_w5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w5.setGeometry(QtCore.QRect(70, 310, 51, 20))
        self.lineEdit_w5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w5.setText("")
        self.lineEdit_w5.setObjectName("lineEdit_w5")
        self.lineEdit_w6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_w6.setGeometry(QtCore.QRect(70, 340, 51, 20))
        self.lineEdit_w6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_w6.setText("")
        self.lineEdit_w6.setObjectName("lineEdit_w6")
        self.Button_modify_weapon = QtWidgets.QPushButton(self.centralwidget)
        self.Button_modify_weapon.setGeometry(QtCore.QRect(20, 370, 75, 23))
        self.Button_modify_weapon.setObjectName("Button_modify_weapon")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(0, 450, 801, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(130, 149, 20, 311))
        self.line_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(170, 160, 51, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(250, 160, 51, 20))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(327, 160, 51, 20))
        self.label_23.setObjectName("label_23")
        self.lineEdit_j6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j6.setEnabled(False)
        self.lineEdit_j6.setGeometry(QtCore.QRect(149, 341, 71, 20))
        self.lineEdit_j6.setText("")
        self.lineEdit_j6.setObjectName("lineEdit_j6")
        self.lineEdit_j2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j2.setEnabled(False)
        self.lineEdit_j2.setGeometry(QtCore.QRect(149, 221, 71, 20))
        self.lineEdit_j2.setText("")
        self.lineEdit_j2.setObjectName("lineEdit_j2")
        self.lineEdit_j5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j5.setEnabled(False)
        self.lineEdit_j5.setGeometry(QtCore.QRect(149, 311, 71, 20))
        self.lineEdit_j5.setText("")
        self.lineEdit_j5.setObjectName("lineEdit_j5")
        self.lineEdit_j3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j3.setEnabled(False)
        self.lineEdit_j3.setGeometry(QtCore.QRect(149, 251, 71, 20))
        self.lineEdit_j3.setText("")
        self.lineEdit_j3.setObjectName("lineEdit_j3")
        self.lineEdit_j4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j4.setEnabled(False)
        self.lineEdit_j4.setGeometry(QtCore.QRect(149, 281, 71, 20))
        self.lineEdit_j4.setText("")
        self.lineEdit_j4.setObjectName("lineEdit_j4")
        self.lineEdit_j1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j1.setEnabled(False)
        self.lineEdit_j1.setGeometry(QtCore.QRect(149, 191, 71, 20))
        self.lineEdit_j1.setText("")
        self.lineEdit_j1.setObjectName("lineEdit_j1")
        self.lineEdit_j8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j8.setEnabled(False)
        self.lineEdit_j8.setGeometry(QtCore.QRect(149, 401, 71, 20))
        self.lineEdit_j8.setText("")
        self.lineEdit_j8.setObjectName("lineEdit_j8")
        self.lineEdit_j7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_j7.setEnabled(False)
        self.lineEdit_j7.setGeometry(QtCore.QRect(149, 371, 71, 20))
        self.lineEdit_j7.setText("")
        self.lineEdit_j7.setObjectName("lineEdit_j7")
        self.lineEdit_jl2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl2.setGeometry(QtCore.QRect(240, 220, 51, 20))
        self.lineEdit_jl2.setText("")
        self.lineEdit_jl2.setObjectName("lineEdit_jl2")
        self.lineEdit_jl8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl8.setGeometry(QtCore.QRect(240, 400, 51, 20))
        self.lineEdit_jl8.setText("")
        self.lineEdit_jl8.setObjectName("lineEdit_jl8")
        self.lineEdit_jl3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl3.setGeometry(QtCore.QRect(240, 250, 51, 20))
        self.lineEdit_jl3.setText("")
        self.lineEdit_jl3.setObjectName("lineEdit_jl3")
        self.lineEdit_jl4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl4.setGeometry(QtCore.QRect(240, 280, 51, 20))
        self.lineEdit_jl4.setText("")
        self.lineEdit_jl4.setObjectName("lineEdit_jl4")
        self.lineEdit_jl6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl6.setGeometry(QtCore.QRect(240, 340, 51, 20))
        self.lineEdit_jl6.setText("")
        self.lineEdit_jl6.setObjectName("lineEdit_jl6")
        self.lineEdit_jl5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl5.setGeometry(QtCore.QRect(240, 310, 51, 20))
        self.lineEdit_jl5.setText("")
        self.lineEdit_jl5.setObjectName("lineEdit_jl5")
        self.lineEdit_jl7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl7.setGeometry(QtCore.QRect(240, 370, 51, 20))
        self.lineEdit_jl7.setText("")
        self.lineEdit_jl7.setObjectName("lineEdit_jl7")
        self.lineEdit_jl1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_jl1.setGeometry(QtCore.QRect(240, 190, 51, 20))
        self.lineEdit_jl1.setText("")
        self.lineEdit_jl1.setObjectName("lineEdit_jl1")
        self.comboBox_tj1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj1.setGeometry(QtCore.QRect(310, 190, 81, 22))
        self.comboBox_tj1.setObjectName("comboBox_tj1")
        self.comboBox_tj2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj2.setGeometry(QtCore.QRect(310, 220, 81, 22))
        self.comboBox_tj2.setObjectName("comboBox_tj2")
        self.comboBox_tj3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj3.setGeometry(QtCore.QRect(310, 250, 81, 22))
        self.comboBox_tj3.setObjectName("comboBox_tj3")
        self.comboBox_tj4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj4.setGeometry(QtCore.QRect(310, 280, 81, 22))
        self.comboBox_tj4.setObjectName("comboBox_tj4")
        self.comboBox_tj8 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj8.setGeometry(QtCore.QRect(310, 400, 81, 22))
        self.comboBox_tj8.setObjectName("comboBox_tj8")
        self.comboBox_tj5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj5.setGeometry(QtCore.QRect(310, 310, 81, 22))
        self.comboBox_tj5.setObjectName("comboBox_tj5")
        self.comboBox_tj7 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj7.setGeometry(QtCore.QRect(310, 370, 81, 22))
        self.comboBox_tj7.setObjectName("comboBox_tj7")
        self.comboBox_tj6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_tj6.setGeometry(QtCore.QRect(310, 340, 81, 22))
        self.comboBox_tj6.setObjectName("comboBox_tj6")
        self.Button_modify_general = QtWidgets.QPushButton(self.centralwidget)
        self.Button_modify_general.setGeometry(QtCore.QRect(210, 430, 75, 23))
        self.Button_modify_general.setObjectName("Button_modify_general")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(400, 149, 20, 311))
        self.line_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(550, 160, 51, 20))
        self.label_24.setObjectName("label_24")
        self.Button_tulong = QtWidgets.QPushButton(self.centralwidget)
        self.Button_tulong.setGeometry(QtCore.QRect(450, 190, 101, 23))
        self.Button_tulong.setObjectName("Button_tulong")
        self.Button_jingshi = QtWidgets.QPushButton(self.centralwidget)
        self.Button_jingshi.setGeometry(QtCore.QRect(600, 190, 101, 23))
        self.Button_jingshi.setObjectName("Button_jingshi")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(410, 240, 391, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setEnabled(False)
        self.textBrowser.setGeometry(QtCore.QRect(430, 260, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "攻城掠地GM工具"))
        self.label.setText(_translate("mainWindow", "IP："))
        self.label_2.setText(_translate("mainWindow", "端口："))
        self.label_3.setText(_translate("mainWindow", "用户名："))
        self.label_4.setText(_translate("mainWindow", "密码："))
        self.Button_connectDB.setText(_translate("mainWindow", "连接数据库"))
        self.Button_getPlayerList.setText(_translate("mainWindow", "获取玩家列表"))
        self.Button_selectPlayer.setText(_translate("mainWindow", "选定玩家"))
        self.label_5.setText(_translate("mainWindow", "银币："))
        self.label_6.setText(_translate("mainWindow", "铁："))
        self.label_7.setText(_translate("mainWindow", "粮食："))
        self.label_8.setText(_translate("mainWindow", "木材："))
        self.label_10.setText(_translate("mainWindow", "金币："))
        self.label_12.setText(_translate("mainWindow", "等级："))
        self.Button_modify_Base.setText(_translate("mainWindow", "修改"))
        self.label_13.setText(_translate("mainWindow", "兵器"))
        self.label_14.setText(_translate("mainWindow", "乌蚕鞭"))
        self.label_15.setText(_translate("mainWindow", "修罗盾"))
        self.label_16.setText(_translate("mainWindow", "护军符"))
        self.label_17.setText(_translate("mainWindow", "等级"))
        self.label_18.setText(_translate("mainWindow", "血滴子"))
        self.label_19.setText(_translate("mainWindow", "禁军令"))
        self.label_20.setText(_translate("mainWindow", "八卦袋"))
        self.Button_modify_weapon.setText(_translate("mainWindow", "修改"))
        self.label_21.setText(_translate("mainWindow", "武将"))
        self.label_22.setText(_translate("mainWindow", "等级"))
        self.label_23.setText(_translate("mainWindow", "目标武将"))
        self.Button_modify_general.setText(_translate("mainWindow", "修改"))
        self.label_24.setText(_translate("mainWindow", "老牛逼了"))
        self.Button_tulong.setText(_translate("mainWindow", "送一个真屠龙"))
        self.Button_jingshi.setText(_translate("mainWindow", "送一个顶级晶石"))
        self.textBrowser.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">随便说点啥吧，我觉得我会火!!!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">哈哈哈</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">qq：291257487</span></p></body></html>"))
